# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fd10aa695f9ab597be02282fe326aee32984866ba6b05f9e9d6b92add7bbf397a474eebe0cb9542dc959c207cda5d06fca078ac5565addd259654901af84cfbe

test:
  secret_key_base: 45d5d62574a1b69746d34df0d71c209f01b822a435f0d2e29f4b7d59492adb5e80fe2fa95fe8923c0f08b8e7209df1ef3b246cd130c0ade9e78f657219ddd2d2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
